# Generated by Django 5.2.4 on 2026-08-10 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tdee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calorie_difference', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_condition', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('physical_activity', models.CharField(choices=[('little', 'Little'), ('moderate', 'Moderate'), ('too_much', 'Too much')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('gram', 'Gram'), ('piece', 'Piece'), ('ml', 'Milliliter')], max_length=10)),
                ('calories_per_unit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='main.dailyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
