# Generated by Django 5.2.4 on 2026-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='bmr',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='calorie_difference',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='tdee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
